on: [push]

env:
  CARGO_TERM_COLOR: always
  MACOS_DEPLOYMENT_TARGET: 10.15

name: Check OSX
jobs:
  check:
    strategy:
      matrix:
        os: [macos-14, macos-12]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/setup-nasm@v1
      - uses: Swatinem/rust-cache@v2
        
      - name: Check without default features
        run: cargo check --no-default-features --features notan/shaderc
        if: matrix.os == 'macos-14'

      # - name: Run arm build
      #   run: cargo build
      #   if: matrix.os == 'macos-14'

      - name: intel heif test
        run: |
          rustc --version --verbose
          brew install libheif
          cargo install cargo-bundle
          cargo bundle --release --features "notan/shaderc heif"
          otool -L target/release/bundle/osx/oculante.app/Contents/MacOS/oculante
          mkdir target/release/bundle/osx/oculante.app/Contents/Frameworks/
          cp /usr/local/opt/libheif/lib/libheif.1.dylib target/release/bundle/osx/oculante.app/Contents/Frameworks/
          cp /usr/local/opt/x265/lib/libx265.209.dylib target/release/bundle/osx/oculante.app/Contents/Frameworks/
          cp /usr/local/opt/libde265/lib/libde265.0.dylib target/release/bundle/osx/oculante.app/Contents/Frameworks/
          cp /usr/local/opt/aom/lib/libaom.3.dylib target/release/bundle/osx/oculante.app/Contents/Frameworks/
          cp /usr/local/opt/webp/lib/libsharpyuv.0.dylib target/release/bundle/osx/oculante.app/Contents/Frameworks/
          cp /usr/local/opt/libvmaf/lib/libvmaf.3.dylib target/release/bundle/osx/oculante.app/Contents/Frameworks/
          install_name_tool -change /usr/local/opt/libheif/lib/libheif.1.dylib "@executable_path/../Frameworks/libheif.1.dylib" target/release/bundle/osx/oculante.app/Contents/MacOS/oculante
          install_name_tool -add_rpath "@executable_path/../Frameworks/libx265.209.dylib" target/release/bundle/osx/oculante.app/Contents/MacOS/oculante
          install_name_tool -add_rpath "@executable_path/../Frameworks/libde265.0.dylib" target/release/bundle/osx/oculante.app/Contents/MacOS/oculante
          install_name_tool -add_rpath "@executable_path/../Frameworks/libaom.3.dylib" target/release/bundle/osx/oculante.app/Contents/MacOS/oculante
          install_name_tool -add_rpath "@executable_path/../Frameworks/libsharpyuv.0.dylib" target/release/bundle/osx/oculante.app/Contents/MacOS/oculante
          install_name_tool -add_rpath "@executable_path/../Frameworks/libvmaf.3.dylib" target/release/bundle/osx/oculante.app/Contents/MacOS/oculante
          install_name_tool -change /usr/local/opt/x265/lib/libx265.209.dylib "@executable_path/../Frameworks/libx265.209.dylib" target/release/bundle/osx/oculante.app/Contents/Frameworks/libheif.1.dylib
          install_name_tool -change /usr/local/opt/libde265/lib/libde265.0.dylib "@executable_path/../Frameworks/libde265.0.dylib" target/release/bundle/osx/oculante.app/Contents/Frameworks/libheif.1.dylib
          install_name_tool -change /usr/local/opt/aom/lib/libaom.3.dylib "@executable_path/../Frameworks/libaom.3.dylib" target/release/bundle/osx/oculante.app/Contents/Frameworks/libheif.1.dylib
          install_name_tool -change /usr/local/opt/webp/lib/libsharpyuv.0.dylib "@executable_path/../Frameworks/libsharpyuv.0.dylib" target/release/bundle/osx/oculante.app/Contents/Frameworks/libheif.1.dylib
          install_name_tool -change /usr/local/opt/libvmaf/lib/libvmaf.3.dylib "@executable_path/../Frameworks/libvmaf.3.dylib" target/release/bundle/osx/oculante.app/Contents/Frameworks/libaom.3.dylib
          otool -L target/release/bundle/osx/oculante.app/Contents/MacOS/oculante
          cp Info.plist target/release/bundle/osx/oculante.app/Contents/Info.plist
        if: matrix.os == 'macos-12'

      - name: Zip Mac Intel Bundle
        run: mv target/release/bundle/osx/oculante.app . && zip -r oculante_app_intel.zip oculante.app
        if: matrix.os == 'macos-12'

      - name: Archive intel build
        uses: actions/upload-artifact@v4
        with:
          name: intel_build
          path: oculante_app_intel.zip
        if: matrix.os == 'macos-12'
        
      - name: arm heif test
        run: |
          rustc --version --verbose
          brew install libheif
          cargo install cargo-bundle
          cargo bundle --release --features "notan/shaderc heif"
          otool -L target/release/bundle/osx/oculante.app/Contents/MacOS/oculante
          mkdir target/release/bundle/osx/oculante.app/Contents/Frameworks/
          cp /opt/homebrew/opt/libheif/lib/libheif.1.dylib target/release/bundle/osx/oculante.app/Contents/Frameworks/
          cp /opt/homebrew/opt/x265/lib/libx265.209.dylib target/release/bundle/osx/oculante.app/Contents/Frameworks/
          cp /opt/homebrew/opt/libde265/lib/libde265.0.dylib target/release/bundle/osx/oculante.app/Contents/Frameworks/
          cp /opt/homebrew/opt/aom/lib/libaom.3.dylib target/release/bundle/osx/oculante.app/Contents/Frameworks/
          cp /opt/homebrew/opt/webp/lib/libsharpyuv.0.dylib target/release/bundle/osx/oculante.app/Contents/Frameworks/
          cp /opt/homebrew/opt/libvmaf/lib/libvmaf.3.dylib target/release/bundle/osx/oculante.app/Contents/Frameworks/
          install_name_tool -change /opt/homebrew/opt/libheif/lib/libheif.1.dylib "@executable_path/../Frameworks/libheif.1.dylib" target/release/bundle/osx/oculante.app/Contents/MacOS/oculante
          install_name_tool -add_rpath "@executable_path/../Frameworks/libx265.209.dylib" target/release/bundle/osx/oculante.app/Contents/MacOS/oculante
          install_name_tool -add_rpath "@executable_path/../Frameworks/libde265.0.dylib" target/release/bundle/osx/oculante.app/Contents/MacOS/oculante
          install_name_tool -add_rpath "@executable_path/../Frameworks/libaom.3.dylib" target/release/bundle/osx/oculante.app/Contents/MacOS/oculante
          install_name_tool -add_rpath "@executable_path/../Frameworks/libsharpyuv.0.dylib" target/release/bundle/osx/oculante.app/Contents/MacOS/oculante
          install_name_tool -add_rpath "@executable_path/../Frameworks/libvmaf.3.dylib" target/release/bundle/osx/oculante.app/Contents/MacOS/oculante
          install_name_tool -change /opt/homebrew/opt/x265/lib/libx265.209.dylib "@executable_path/../Frameworks/libx265.209.dylib" target/release/bundle/osx/oculante.app/Contents/Frameworks/libheif.1.dylib
          install_name_tool -change /opt/homebrew/opt/libde265/lib/libde265.0.dylib "@executable_path/../Frameworks/libde265.0.dylib" target/release/bundle/osx/oculante.app/Contents/Frameworks/libheif.1.dylib
          install_name_tool -change /opt/homebrew/opt/aom/lib/libaom.3.dylib "@executable_path/../Frameworks/libaom.3.dylib" target/release/bundle/osx/oculante.app/Contents/Frameworks/libheif.1.dylib
          install_name_tool -change /opt/homebrew/opt/webp/lib/libsharpyuv.0.dylib "@executable_path/../Frameworks/libsharpyuv.0.dylib" target/release/bundle/osx/oculante.app/Contents/Frameworks/libheif.1.dylib
          install_name_tool -change /opt/homebrew/opt/libvmaf/lib/libvmaf.3.dylib "@executable_path/../Frameworks/libvmaf.3.dylib" target/release/bundle/osx/oculante.app/Contents/Frameworks/libaom.3.dylib
          otool -L target/release/bundle/osx/oculante.app/Contents/MacOS/oculante
          cp Info.plist target/release/bundle/osx/oculante.app/Contents/Info.plist
        if: matrix.os == 'macos-14'
        
      - name: Zip Mac Arm Bundle
        run: mv target/release/bundle/osx/oculante.app . && zip -r oculante_app_arm.zip oculante.app
        if: matrix.os == 'macos-14'

      - name: Archive arm build
        uses: actions/upload-artifact@v4
        with:
          name: arm_build
          path: oculante_app_arm.zip
        if: matrix.os == 'macos-14'
        
      - name: arm  test
        run: |
          rustc --version --verbose
          cargo install cargo-bundle
          cargo bundle --release --features "notan/shaderc"
        if: matrix.os == 'macos-14'
        
      - name: Zip Mac Arm Bundle
        run: |
          rm -rf oculante.app
          mv target/release/bundle/osx/oculante.app . && zip -r oculante_app_arm_noheif.zip oculante.app
        if: matrix.os == 'macos-14'

      - name: Archive arm build
        uses: actions/upload-artifact@v4
        with:
          name: arm_build2
          path: oculante_app_arm_noheif.zip
        if: matrix.os == 'macos-14'