name: NetBSD check no default features

on: [push]

jobs:
  test:
    runs-on: macos-12
    name: Test in NetBSD
    steps:
    - uses: actions/checkout@v2
    - name: Test in NetBSD
      id: test
      uses: vmactions/netbsd-vm@v0
      with:
        mem: 4096
        usesh: true
        copyback: false
        prepare: |
          pkg_add curl pkg-config cmake openssl libX11 fontconfig freetype2 gdk-pixbuf2 cairo pango atk glib2 libXrender libxcb nasm perl
          # gtk3 and libX11 seem to be missing ^^
          # PKG_PATH="http://cdn.NetBSD.org/pub/pkgsrc/packages/NetBSD/$(uname -p)/$(uname -r|cut -f '1 2' -d.)/All/"
          # export PKG_PATH
          # pkg_add pkgin
          # pkgin search gtk3
          curl https://sh.rustup.rs -sSf | sh -s -- -y --profile minimal
        run: |
          PATH=$HOME/.cargo/bin:$PATH
          export PATH
          cargo check --no-default-features
