name: NetBSD check

on: [push]

jobs:
  test:
    runs-on: macos-12
    name: Test in NetBSD
    env:
      MYTOKEN : ${{ secrets.MYTOKEN }}
      MYTOKEN2: "value2"
    steps:
    - uses: actions/checkout@v2
    - name: Test in NetBSD
      id: test
      uses: vmactions/netbsd-vm@v0
      with:
        envs: 'MYTOKEN MYTOKEN2'
        usesh: true
        prepare: |
          pkg_add curl pkg-config cmake openssl libX11 fontconfig freetype2 gdk-pixbuf2 cairo pango atk glib2 gtk3 gtk3+-3.24.33
          # gtk3 and libX11 seem to be missing ^^
          # PKG_PATH="http://cdn.NetBSD.org/pub/pkgsrc/packages/NetBSD/$(uname -p)/$(uname -r|cut -f '1 2' -d.)/All/"
          # export PKG_PATH
          # pkg_add pkgin
          # pkgin search gtk3
          curl https://sh.rustup.rs -sSf | sh -s -- -y --profile minimal
        run: |
          PATH=$HOME/.cargo/bin:$PATH
          export PATH
          cargo check --no-default-features
